import "./components/logo.js"
import "./components/hero.js"
import "./components/nav.js"
import "./components/tarjeta.js"
import "./components/header.js"
import "./components/footer.js"
import "./components/club-form.js"
